swccgpc/swccg-card-json

Dark.json

Added missing light/dark icons for Tatooine: Mos Eisley (V) from Virtual Block 1.

Tatooine-Mos-Eisley-V

---

Dark.json

Darth Maul, Lone Hunter is Deploy = 6 (not 7) in the errata'd Set 3 PDF.

darth-maul-lone-hunter

---

Dark.json
Light.json

I want to be able to use this icon when cross-referencing with: https://raw.githubusercontent.com/PlayersCommittee/gemp-swccg-public/master/gemp-swccg-server/src/main/resources/swccgFormats.json.  This way I can determine which cards are banned in formats where MAINTENANCE is included in the bannedIcons list.

Added Maintenance icon.

---

Dark.json
Light.json

I want to be able to use this icon when cross-referencing with: https://raw.githubusercontent.com/PlayersCommittee/gemp-swccg-public/master/gemp-swccg-server/src/main/resources/swccgFormats.json. This way I can determine which cards are banned in formats where DEFENSIVE_SHIELD is included in the bannedIcons list.

Added Defensive Shield icon.

---

Dark.json
Light.json

Replaced fancy quote mark with single tick mark.
These characters don't work well in Holotable and aren't consistent with other cards that have an apostrophe.  (e.g. Han's Dice)

Single Quote

---

Dark.json

The admiral should be rarity C2 to match the Bespin Motors Void Spider THX 1138 card rarity he is based on.

Admiral Trench

---

Light.json

[Immune to Sense] => (Immune to Sense)
There are one or two more instances of this, but was only interested in fixing this one because it is recent errata.

Odin Nesloor & First Aid

---

Dark.json

Re-ordered icons so warrior and permanent weapon are "adjacent".
Re-added (AI) version as the image is now available.

Aurra Sing With Blaster Rifle

---

Dark.json
Light.json

Added Lore: Blank to some defensive shields consistent with other defensive shields with blank lore.
Added actual lore text to some defensive shields where the card image includes the lore from the virtualized case.

Blank Lore Shields

---

Dark.json

I think the , in Slave I, Symbol of Fear messed up on someone's JSON parser at some point, and the matching key has separated them as though they were two different array elements.

Fix Slave I, Symbol Of Fear in matching lists

---

Dark.json
Light.json

Fixed issue where three cards had duplicate IDs.  This caused three cards to not appear in the Comlink app.

Duplicate id fixes

---

Light.json

I noticed this inconsistency.  This brings it in line with the other creatures.
As a side note, I'm not sure ferocity is being handled the same as all other fields now, and I think we may want to update all ferocity's that contain an asterisk to actually have the asterisk in the data.  That way the data represents exactly what is printed on the card.

Fixed LS Space Slug ferocity.

---

sets.json

For now we list it as March 9 release of 6 cards, but later we update the date and size when the rest of the set releases.

Updating sets.json for Set 18

---

Dark.json
Light.json

1. Errata for three Zero Hour cards.
2. Removed the blanked cards Drop V and Thrown Back V.
3. As discussed with EBT, all AI cards (even the Decipher ones) now use an underscore, ending with _ai.gif instead of just ai.gif.  I tested every updated image link to be sure they all worked.
4. Added many rulings and fixes.

Sept errata, AI underscore, rulings, fixes

---

Dark.json
DarkPreErrata.json
Light.json
LightPreErrata.json
sets.json

Added new Set 20 cards (image links have been tested)
Applied Set 20 errata to existing cards (including editing their rulings accordingly)
Added the 2020 AIs (image links have been tested)
Added new DarkPreErrata.json and LightPreErrata.json with just the old versions of the cards changed for Set 20. Think of this small sampling as a first draft we can look at and continue to improve.

Set 20, 2020 AIs, PreErrata files, minor fixes

---

Light.json

Grappling Hook (V) was listed as the underlying card for itself
Removed uniqueness dot from Another Pathetic Lifeform & Security Control

Underlying card fixes

---

Dark.json
Light.json

Most of the issues are cases where one side was linking to a slip from the opposite side.  But there were a few other random issues fixed as well.

Fixes to printable slip URLs

---

Dark.json
Light.json

- Add underlying data for all V22 cards
- Update underlying data format for cards are underlying for V22 that were underlying cards for other V cards
- Update text for both V22 Hoth sites to include the Marker designation

add underlying card data for v22

---

Light.json

A couple lines in the Light file were pointing to the DS slips instead of LS slips.  Affects Jakku system and Jakku Tuanul Village.

printableSlipUrl fixes

---

Dark.json

Some weird mixups happened between Black 2, Black 2 (V), and Black 5 with printable slips.  All have been carefully double-checked, and this fixes them to how they should be.

Minor printableSlip fixes

---

Dark.json
Light.json

Added missing vkit slip for Han... Solo
Moved Ortugg's vkit slip from an errata on the original to a v-slip on the virtual
Noted that Ortugg and Ortugg (V) are guards

Vkit fixes

---

Dark.json
Light.json

Fixing many instances where the regular card vkit slip linked to a Hologram AI, and the Hologram AI was missing a vkit slip.
Now the regular card links to the regular slip and the hologram AI links to the hologram AI slip.

Vkit slip fixes

---

Dark.json
Light.json

Back when vkit slip URLs were automatically assigned to cards, the process that did so was not totally perfect, some mistakes slipped through.
I became aware of a specific recurring issue where sometimes vslips were assigned to the Decipher card as an errata slip (such as Captain Bewil V slip being assigned to regular Captain Bewil), and/or were sometimes assigned to a card of the same title on the opposite side of the Force (such as the LS Weather Vane V slip being assigned to DS Weather Vane).
I figured out a semi-automated, semi-manual way to detect instances of this issue without too much trouble for a one-time mass fix.  This PR is the mass fix.  There are about 25 instances of badly assigned VKit slips being repaired in this PR.

VKit URL Fixes
