swccgpc/swccg-card-json

- Dark.json
- Light.json
Updated files for October 2020 Errata.
> October 2020 Errata

- Dark.json
- Light.json
Fixed mispellings in Light.json.
Formatted document for consistency.
> Sensative => Sensitive

- Dark.json
> Interupt => Interrupt

- Dark.json
- Light.json
Found and removed trailing slashes on many cards, mostly in the conceptBy property.
> RemoveTrailingSlashes

- Dark.json
> OurFirstCatchOfTheDay

- Dark.json
Updated Dark Creature Defensive Text
> dark-creature-defenses

- Dark.json
Filled out game text of Commence Primary Ignition.
> commence-primary-ignition

- Dark.json
> missing-force-icons

- Dark.json
> count-dooku

- Dark.json
Fixed Shadows Of The Empire Gamte Text
> shadows-of-the-empire

- sets.json
Working to be able to connect this repo's json data to the card/set data used by GEMP.
> Added sets.json.  This allows you to map to and from GEMP sets.

- Dark.json
Replaced umlaut a with regular a as they don't work well in Holotable and just make life simpler.
> Dryden Vos

- Dark.json
> Target The Main Generator

- Light.json
Added missing Episode I icon per erratad Set 10 PDF.
> Ambush (V)

- Dark.json
- Light.json
- Rename all occurances of "Demo Deck" to be "Virtual Premium Set".
> Update all cards in the "Demo Deck" to instead be in the "Virtual

- Dark.json
Removed duplicate /cards string in the image link.
> Insignificant Rebellion (V)

- Dark.json
Fixed wording of gametext consistent with current PDF.
> Kir Kanos (V)

- Dark.json
- Light.json
Deploy on Table => Deploy on table
> Deploy on Table

- Light.json
> Leia's Resistance Transport

- Dark.json
Added "here" and parenthesis per CDF.
> Moff Gideon

- Light.json
A-Wing => A-wing for consistency to all cards that reference A-wings.
> Tallie Lintra In Blue 1

- Light.json
The ... special character makes life difficult in Holotable.  We did away with special characters in other cards like Qi'ra and Teras Kasi.
> Han... Solo

- Light.json
> Affect Mind (V)

- Dark.json
Use standard tick mark instead of fancy apostrophe mark for consistency.
> Stalker (V)

- Light.json
Standard ' mark instead of fancy apostrophe.
> Din Djarin

- Light.json
Standard ' instead of fancy apostrophe.
> Beaumont Kin

- Light.json
Spacing consistent with other USED / LOST text (and for CDF export).
> Rescue In The Clouds (V)

- Dark.json
Added uniqueness dot and standardized (Immune to Alter)
> Course And Rough And Irritating

- Light.json
Added uniqueness dot and standardized (Immune to Alter)
> I Don't Like Sand

- Light.json
Updated reference to [Set 0] consistent with other cards that reference a virtual set specific card (Dathomir: Maul's Chambers).
> Hear Me Baby, Hold Together (V)

- Light.json
[Light Side Force] => [Light Side] for consistency.
Scomp Link => Scomp link for correctness.
> R2-D2 (Artoo-Detoo) (V)

- Light.json
> Why Does Everyone Want To Go Back To Jakku?!

- Dark.json
> Dr. Chelli Lona Aphra

- Dark.json
> I Will Finish What You Started

- Dark.json
- Light.json
[Immune to Alter.] => (Immune to Alter.) for consistency.
> Immune to Alter

- Light.json
> Someone Who Loves You

- Dark.json
- Light.json
Added some rulings and a bunch of fixes. Many of the fixes had to do with uniqueness dots in title and the uniqueness attribute field.
> Added rulings and fixes

- Light.json
Fixed encoding issues.
Fixed single image reference.
> Resolved Minor Encoding and Image Ref Issues

- Dark.json
- Light.json
About 25 rulings and some assorted fixes, including the Rukh title typo.
> July 9 2021 Rulings Fixes

- Dark.json
- Light.json
VSet 16 plus a few small fixes.
> Virtual Set 16

- Light.json
> Escape Pod & We're Doom Image Reference

- Dark.json
- Light.json
- sets.json
Also added some abbreviations because Tom recently made them searchable by default (e.g. you can type HCF right in the title box and it works!)
> VIRTUAL SET 17! Plus rulings and fixes.

- Dark.json
- Light.json
Adds over 30 new AIs plus other improvements.
> Added AIs, rulings, fixes

- Dark.json
- Light.json
> Fixed uniqueness fields. Fixed JSON violations.

- Dark.json
Accidentally pushed these two branches to the main repo instead of my fork, I will fix that in the future.
> Moved Advosze rulings from AAT Laser Cannon to Advosze.

- Light.json
This is an example PR, to demonstrate how we *could* use HTML in the rulings strings moving forward.
***Do *not* merge yet!***
In Comlink, which will soon support displaying rulings, you can see an example below.
**Current:**
**With HTML:**
Obviously there is some neat formatting you could do with bold/italics/breaks, etc.  Could be very handy as rulings continue to be added!
> Updated "A New Secret Base" rulings to make use of HTML.

- Dark.json
- DarkLegacy.json
- Light.json
- LightLegacy.json
- sets.json
Updated references to Reflections II -> Reflections 2, and Reflections III -> Reflections 3.
> Updated references to Reflections Roman Numerals

- Dark.json
- Light.json
Fixed typo and updated <> to ♢ in rulings, to fix HTML rendering issue on Comlink.
> Fixed typo and updated <> to ♢ in rulings, to fix HTML rendering issue on Comlink.

- Dark.json
- Light.json
- sets.json
Also fixed some errors and added some rulings.
> Set 18 added!

- Dark.json
- Light.json
2 commits because I had a tiny error in the first commit
> Many fixes and rulings

- Dark.json
- Light.json
Put in the July 1 errata.  Also added a ton of rulings, as well as fixes for recently reported errors.
> Fixes, rulings, recent errata

- Light.json
Fixing minor errors on LS Lothal
> Fix title/img link on Lothal

- Dark.json
- DarkLegacy.json
- Light.json
- LightLegacy.json
Mostly just rulings for Set 19 today.  More variety of extra card info, fixes, and more to come in a later update.
> Set 19 rulings, Thrawn (V) AI

- Dark.json
- DarkPreErrata.json
- Light.json
- sets.json
Updates DS Lothal with errata and adds the 6 Set 21 Preview cards.  Also fixes a few minor things.
> Set 21 Preview and Errata

- Light.json
- LightPreErrata.json
June 1 errata and a few whitespace fixes.  Small update
> June 1 errata

- Dark.json
- Light.json
Fixes some capitalization issues and typos in underlying cards
> Underlying card fixes

- Dark.json
- Light.json
- LightLegacy.json
- LightPreErrata.json
- sets.json
Minor fixes.  Many more rounds of fixes to come, decided to break it up into smaller PRs that I can work on a bit at a time instead of trying to get everything through in a giant update.
> Minor fixes

- Dark.json
- DarkLegacy.json
- DarkPreErrata.json
- Light.json
- LightPreErrata.json
Added all the missing recent errata and implemented some other fixes such as typos etc.
> Errata and fixes

- Dark.json
- Light.json
A small batch but trying to keep these going on a regular basis :)
> Minor fixes and rulings

- Dark.json
- DarkPreErrata.json
- Light.json
- LightPreErrata.json
Imperial Detention errata
A Brave Resistance blanked (removed)
Ralltiir Operations (V) blanked (removed)
> July 15 2023 Errata

- Dark.json
- Light.json
Some minor fixes missed in the previous cleanup.  Have done several passes using a variety of different error-checking techniques on each pass.  Feeling really good about the accuracy of the data at this stage.
> Additional printableSlipUrl fixes

- Dark.json
- Light.json
Fixed and added data regarding C-Slip AIs so that they'll display proper images and listings in Scomp.
> C-Slip AI Fixes/Additions

- Dark.json
- Light.json
Various small rulings and fixes
> Rulings and fixes

- Dark.json
- Light.json
- LightPreErrata.json
Adding the data for the latest batch alternate image cards being publicly released.  Some unrelated minor fixes are also included in this PR.
> Alternate Images Dec 2023

- Dark.json
- DarkPreErrata.json
- Light.json
- LightPreErrata.json
- sets.json
> Set 23 Preview and Dec 2023 Errata

- Dark.json
> Special Character

- Light.json
- LightPreErrata.json
Breaking the Set 24 LS errata up into 2-3 PRs because there is so much.
> Set 24 Errata - Light (part 1)

- Dark.json
- Light.json
- LightPreErrata.json
> Set 24 Errata - Light (part 2 of 3)

- Dark.json
- Light.json
- sets.json
> Add Set 25 cards

- Dark.json
- Light.json
A handful of small fixes to errors, some new and some old
> Small fixes

- Dark.json
- Light.json
Mostly adding rulings for Scomp and Comlink, but a few fixes too.
> Set 25 rulings and fixes
